global:
  logLevel: 10
  logFlushFrequency: 5
  watchdogSec: 10

logging:
  level: info

debug:
  address: "127.0.0.1:6831"
  pprof: true
  expvar: true
  metrics: true

tracing:
  httpBody: true       # log http request body
  httpHeader: true     # log http request header
  respTraceId: true    # inject trace id into response header
  jaeger:
    serviceName: helo
    reporter:
      localAgentHostPort: 127.0.0.1:6831
      logSpans: false

apiserver:
  externalHost:
  bindAddress: 0.0.0.0
  bindPort: 8080
  corsAllowedOriginList:
  hstsDirectives:
  maxRequestsInFlight: 400
  maxMutatingRequestsInFlight: 200
  requestTimeout: 60
  livezGracePeriod: 0
  minRequestTimeout: 1800
  #shutdownTimeout: 60s
  shutdownDelayDuration: 0
  maxRequestBodyBytes: 3145728
  enablePriorityAndFairness: true

authentication:
  session: true                   # --enable-session-auth
  bootstrapToken: true            # --enable-bootstrap-token-auth
  anonymous: true                 # --anonymous-auth
  tokenAuthFile: ./run/tokens.cvs # --token-auth-file={file-path}
  oidc:
    issuerURL:                    # --oidc-issuer-url
    clientID:                     # --oidc-client-id

authorization:
  policyFile: ./run/abac.json     # --authorization-policy-file={file-path}
  modes:                          # --modes=ABAC,AlwaysAllow
    - ABAC
    #- AlwaysAllow

  
session:
  enabled: true
  storage: "db" # mem | db
  cookieName: "golib-example-sid"
  sidLength: 24
  httpOnly: true
  domain:
  gcInterval: 60
  cookieLifetime: 57600 # 16 * 3600

swagger: # depend http
  enabled: true
  name: "helo"
  url: "/apidocs.json"
  clientId: "1234"
  clientSecret: "1234"
  schemes:
    - name: "BearerToken"
      type: "apiKey"
      fieldName: "authorization"
      valueSource: "header" # can be "header", "query" or "cookie"
#    - name: "OAuth2"
#      type: "accessCode"
#      authorizationURL: "http://localhost/o/oauth2/authorize"
#      tokenURL: "http://localhost/o/oauth2/token"
#    - name: "Base"
#      type: "base"

grpc:
  addr: ":8081"
  maxRecvMsgSize: 1024000

db:
  driver: "sqlite3"
  dsn: "file:helo.db?cache=shared&mode=memory"
  #driver: "mysql"
  #dsn: "root:1234@tcp(localhost:3306)/test?loc=Local&parseTime=true"

auth:
  name: "helo.auth"
