apiserver:
  insecureServing:
    bindAddress: 0.0.0.0
    bindNework: tcp
    bindPort: 8080
    enabled: true
  secureServing:
    enabled: false
  securitySchemes:
    - name: BearerToken
      type: bearer

authentication:
  anonymous: true
  oidc:
    caFile:
    clientID: my-client
    issuerURL: http://localhost:8081
    usernameClaim: username
    groupsClaim: groups

authorization:
  modes:
    - ABAC 
  policyFile: ./abac.json
  alwaysAllowPaths:
    - /apidocs.json
    - /swagger/*
