apiserver:
  insecureServing:
    bindAddress: 0.0.0.0
    bindNework: tcp
    bindPort: 8080
    enabled: true
  secureServing:
    enabled: false
  securitySchemes:
    - name: BearerToken
      type: bearer

authentication:
  anonymous: true

authorization:
  modes:
    - ABAC 
  policyFile: ./abac.json
  alwaysAllowPaths:
    - /apidocs.json
    - /swagger/*
