global:
  logLevel: 1
  logFlushFrequency: 5
  watchdogSec: 10

logging:
  level: info

debug:
  address: "127.0.0.1:6831"
  pprof: true
  expvar: true
  metrics: true

traces:
  debug: false
  serviceName: all-in-one
  contextHeadername: Trace-Id
  otel:
    endpoint: localhost:4317
    insecure: true

apiserver:
  generic:
    enablePriorityAndFairness: true
    goawayChance: 0
    livezGracePeriod: 0
    maxMutatingRequestsInFlight: 200
    maxRequestBodyBytes: 3145728
    maxRequestsInFlight: 400
    minRequestTimeout: 30m0s
    requestTimeout: 1m0s
    shutdownDelayDuration: 0
  insecureServing:
    bindAddress: 0.0.0.0
    bindNework: tcp
    bindPort: 8080
    enabled: false
  secureServing:
    PermitAddressSharing: false
    bindAddress: 0.0.0.0
    bindNework: tcp
    bindPort: 8443
    enabled: true
    http2MaxStreamsPerConnection: 0
    permitPortSharing: false
    serverCert:
      certDir: /var/run/all
      pairName: apiserver
  enableContentionProfiling: true
  enableIndex: false
  enableMetrics: false
  enablePriorityAndFairness: true
  enableProfiling: true
  enableOpenAPI: true


authentication:
  session: true                   # --enable-session-auth
  bootstrapToken: true            # --enable-bootstrap-token-auth
  anonymous: true                 # --anonymous-auth
  tokenAuthFile: ./etc/tokens.cvs # --token-auth-file={file-path}
  oidc:
    issuerURL:                    # --oidc-issuer-url
    clientID:                     # --oidc-client-id

authorization:
  modes:                          # --modes=RBAC,AlwaysAllow
    - RBAC
  #policyFile: ./etc/abac.json     # --authorization-policy-file={file-path}
  rbac:
    configPath: ./etc/rbac        # --rbac-config-path
  alwaysAllowGroups:
    - system:masters
  alwaysAllowPaths:
    - /apidocs.json
    - /swagger/*

session:
  enabled: true
  storage: "db" # mem | db
  storageExtra: "session"
  cookieName: "golib-example-sid"
  sidLength: 24
  httpOnly: true
  domain:
  gcInterval: 60
  cookieLifetime: 57600s # 16 * 3600

grpc:
  addr: ":8081"
  maxRecvMsgSize: 1024000

db:
  driver: "sqlite3"
  dsn: "file:example-all.db?cache=shared&mode=memory"
  databases:
    - name: "apiserver" 
      driver: "sqlite3"
      dsn: "file:example-all-apiserver.db?cache=shared&mode=memory"
  #driver: "mysql"
  #dsn: "root:1234@tcp(localhost:3306)/test?loc=Local&parseTime=true"

auth:
  name: "example-all.auth"
